# Autonomous Kanban two-stage flow and lifecycle

Use this reference when a migration also needs autonomous task creation.

## Two-stage contract

1. Intake creates exactly one root task on the explicitly selected project board.
2. Prefer `--triage` for durable, multi-step, parallel, review-gated, or restart-survivable work.
3. The gateway dispatcher invokes decomposition; the decomposer reads the root, available profiles, profile descriptions, and dependencies, then creates a dependency-aware child graph.
4. Create dependencies at child creation time. Do not create all cards independently and repair links afterward.
5. Workers may create follow-up cards only on the board pinned by `HERMES_KANBAN_BOARD`; they must not infer a board from titles or project names.
6. Use idempotency keys for intake and preserve source/project/criteria metadata.

## Local configuration baseline

```yaml
kanban:
  dispatch_in_gateway: true
  orchestrator_profile: engineering
  default_assignee: engineering
  auto_decompose: true
  auto_decompose_per_tick: 2
  review_dispatch: true
  max_in_progress: 6
```

The exact values are a conservative baseline, not a universal default. Verify the local profile roster before assigning names.

## Gateway/profile lifecycle

- Use one launchd/systemd-managed multiplexing gateway; do not create separate per-profile gateways for project boards.
- After changing Kanban configuration, profile files, or gateway service definitions, restart/reload the single gateway and verify its service definition matches the current Hermes install.
- A running Hermes process or cron subsystem can recreate deleted profile directories. Stop writers before removing a profile, then restart the gateway and re-check served profiles.
- Boards and profiles are separate concepts: deleting a profile does not require deleting its board, and a board does not by itself justify recreating a profile.

## Verification smoke test

Create a verification-only triage root on the target board, decompose it, inspect the parent/child graph and board/workspace metadata, then archive the entire smoke graph. Do not leave verification cards active in a production queue.

## Private configuration repositories

When creating a private Git repository from an agent home, whitelist reviewable configuration files. Exclude credentials, tokens, session transcripts, histories, caches, daemon state, jobs, telemetry, generated bytecode, and other runtime data. Verify both `git ls-files` and `git status` before pushing.
